---
title: "Bruno diversity 033123"
author: "Tom Fu"
date: "2023-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(betapart)
library(vegan)
library(ggplot2)
library(readxl)
library(ggnetwork)
library(tibble)
library("dplyr")
library(phyloseq)
```

# 1. all
## 1.1 data loading and cleaning
```{r}
otu_mat<- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/speciesBrunoOTUTable033123.xlsx") # CORRECT
otu_mat<-otu_mat[!(otu_mat$otu=="FructanSensitivity"),]
species_names = otu_mat$otu
row.names(otu_mat) <- otu_mat$otu
otu_mat <- as.matrix(otu_mat)
otu_mat_t = t(otu_mat)
otu_mat_t <- otu_mat_t[-1,]
class(otu_mat_t)<-"numeric"
```

```{r}
samples_df <- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/brunoMetadata_all_033123.xlsx") # CORRECT
groups<-as.list(samples_df['FsenText'])$FsenText
groups
```
## 1.2 alpha diversity
```{r}
alphaDiversity <- diversity(otu_mat_t, index="shannon")
ANOVAres <- aov(alphaDiversity~groups)

alphaDataframe <- data.frame(alphaDiversity, groups)
write.csv(alphaDataframe, "./outputs/alph_div_df_all.csv")
alphaData_Meds <- alphaDataframe %>%
  group_by(groups) %>%
  summarise(firstQ= quantile(alphaDiversity, prob=0.25, na.rm=TRUE),
            med= quantile(alphaDiversity, prob=0.5, na.rm=TRUE),
            thirdQ= quantile(alphaDiversity, prob=0.75, na.rm=TRUE))

p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity))+
        geom_boxplot(aes(col=groups))+geom_violin(aes(col=groups), alpha=0)+
        ggtitle(paste0("All Diets", " p-value = ", round(summary(ANOVAres)[[1]][["Pr(>F)"]][1], 4)))+
        theme_minimal()+theme(legend.position="none")+
        ylab("Shannon Index")+xlab("fructan sensitivity")+
        geom_text(data= alphaData_Meds, aes(x= groups, y= med, label= round(med,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= firstQ, label= round(firstQ,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= thirdQ, label= round(thirdQ,2)))
p
ggsave(file="./outputs/alpha_div_all_violin.pdf", width=10, height=8, dpi=300)
```

```{r}
alphaDataframe <- data.frame(alphaDiversity, groups)
p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity)) + 
  geom_dotplot(binaxis='y', stackdir='center', aes(col=groups))+
  ggtitle(paste0("All Diets", " p-value = ", round(summary(ANOVAres)[[1]][["Pr(>F)"]][1], 4)))
p
ggsave(file="./outputs/alpha_div_all.pdf", width=10, height=8, dpi=300)
```
## 1.3 beta diversity
```{r}
seqObj <- phyloseq(otu_table(otu_mat_t, taxa_are_rows= FALSE), sample_names(samples_df['FsenText']))
###Beta diversity
ord <- ordinate(seqObj, method = "NMDS", "bray")
NMDSNetworkData <- as.data.frame(ord["points"])
NMDSNetworkData$group <- groups


allxend <- sapply(split(NMDSNetworkData$points.MDS1, NMDSNetworkData$group), mean) # xend_calculated for each group
allyend <- sapply(split(NMDSNetworkData$points.MDS2, NMDSNetworkData$group), mean) # yend_calculated for each group
NMDSNetworkData$xend_calculated <- 0
NMDSNetworkData$yend_calculated <- 0
for (x in 1:nrow(NMDSNetworkData)) {
  NMDSNetworkData$xend_calculated[x] <- unname(allxend[NMDSNetworkData$group[x]])
  NMDSNetworkData$yend_calculated[x] <- unname(allyend[NMDSNetworkData$group[x]])
}
```


```{r}
permanova <- vegan::adonis(otu_table(seqObj)~ groups, permutations=300, method = "bray")
permanova.pval <- permanova$aov.tab[,"Pr(>F)"][1]

p <- ggplot(NMDSNetworkData,
             aes(x = points.MDS1, y = points.MDS2, xend = xend_calculated, yend = yend_calculated, color = group),
             axes=TRUE) +
        geom_point(aes(color = group)) +
        geom_edges(aes(color = group)) +
        geom_nodes(aes(color = group)) +
        xlab("NMDS1") +
        ylab("NMDS2")+
        stat_ellipse(type = "norm", linetype = 2) +
        theme_classic() +
        labs(title = paste0('All Diets', " PERMANOVA p-value = ", round(permanova.pval, 4)))
p 
ggsave(file="./outputs/beta_div_all.pdf", width=10, height=8, dpi=300)
```


```{r}
pdf(file="./outputs/beta_top10_coefs_all.pdf", width=10, height=8)
coef <- coefficients(permanova)["groups1",]
top.coef <- coef[rev(order(abs(coef)))[1:20]]
barplot(sort(top.coef), horiz=T, las=1, main="Top taxa for PERMANOVA - all diets", cex.names=0.4)

```

```{r}
write.csv(sort(top.coef), "./outputs/beta_barplot_data_all.csv")
```



# 2. Baseline
## 2.1 data loading and cleaning
```{r}
otu_mat<- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/speciesBrunoOTUTable_BL_033123.xlsx") # CORRECT
otu_mat<-otu_mat[!(otu_mat$otu=="FructanSensitivity"),]
row.names(otu_mat) <- otu_mat$otu
otu_mat <- as.matrix(otu_mat)
otu_mat_t = t(otu_mat)
otu_mat_t <- otu_mat_t[-1,]
class(otu_mat_t)<-"numeric"
```

```{r}
samples_df <- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/brunoMetadata_BL_033123.xlsx") # CORRECT
groups<-as.list(samples_df['FsenText'])$FsenText
groups
```
## 2.2 alpha diversity
```{r}
alphaDiversity <- diversity(otu_mat_t, index="shannon")
ANOVAres <- aov(alphaDiversity~groups)

alphaDataframe <- data.frame(alphaDiversity, groups)
write.csv(alphaDataframe, "./outputs/alph_div_df_BL.csv")
alphaData_Meds <- alphaDataframe %>%
  group_by(groups) %>%
  summarise(firstQ= quantile(alphaDiversity, prob=0.25, na.rm=TRUE),
            med= quantile(alphaDiversity, prob=0.5, na.rm=TRUE),
            thirdQ= quantile(alphaDiversity, prob=0.75, na.rm=TRUE))

p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity))+
        geom_boxplot(aes(col=groups))+geom_violin(aes(col=groups), alpha=0)+
        ggtitle(paste0("Baseline Diet", " p-value = ", round(summary(ANOVAres)[[1]][["Pr(>F)"]][1], 4)))+
        theme_minimal()+theme(legend.position="none")+
        ylab("Shannon Index")+xlab("fructan sensitivity")+
        geom_text(data= alphaData_Meds, aes(x= groups, y= med, label= round(med,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= firstQ, label= round(firstQ,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= thirdQ, label= round(thirdQ,2)))
p
ggsave(file="./outputs/alpha_div_BL_violin.pdf", width=10, height=8, dpi=300)
```

```{r}
alphaDataframe <- data.frame(alphaDiversity, groups)
p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity)) + 
  geom_dotplot(binaxis='y', stackdir='center', aes(col=groups))+
  ggtitle("Shannon Alpha Diversity - Baseline Diet")
p
ggsave(file="./outputs/alpha_div_BL.pdf", width=10, height=8, dpi=300)
```
## 2.3 beta diversity
```{r}
seqObj <- phyloseq(otu_table(as.matrix(otu_mat_t), taxa_are_rows= FALSE), sample_names(samples_df['FsenText']))
###Beta diversity
ord <- ordinate(seqObj, method = "NMDS", "bray")
NMDSNetworkData <- as.data.frame(ord["points"])
NMDSNetworkData$group <- groups


allxend <- sapply(split(NMDSNetworkData$points.MDS1, NMDSNetworkData$group), mean) # xend_calculated for each group
allyend <- sapply(split(NMDSNetworkData$points.MDS2, NMDSNetworkData$group), mean) # yend_calculated for each group
NMDSNetworkData$xend_calculated <- 0
NMDSNetworkData$yend_calculated <- 0
for (x in 1:nrow(NMDSNetworkData)) {
  NMDSNetworkData$xend_calculated[x] <- unname(allxend[NMDSNetworkData$group[x]])
  NMDSNetworkData$yend_calculated[x] <- unname(allyend[NMDSNetworkData$group[x]])
}
```

```{r}
permanova <- vegan::adonis(otu_table(seqObj)~ groups, permutations=300, method = "bray")
permanova.pval <- permanova$aov.tab[,"Pr(>F)"][1]

p <- ggplot(NMDSNetworkData,
             aes(x = points.MDS1, y = points.MDS2, xend = xend_calculated, yend = yend_calculated, color = group),
             axes=TRUE) +
        geom_point(aes(color = group)) +
        geom_edges(aes(color = group)) +
        geom_nodes(aes(color = group)) +
        xlab("NMDS1") +
        ylab("NMDS2")+
        stat_ellipse(type = "norm", linetype = 2) +
        theme_classic() +
        labs(title = paste0('Baseline Diet', " PERMANOVA p-value = ", round(permanova.pval, 4)))
p 
ggsave(file="./outputs/beta_div_BL.pdf", width=10, height=8, dpi=300)
```

```{r}
pdf(file="./outputs/beta_top10_coefs_BL.pdf", width=10, height=8)
coef <- coefficients(permanova)["groups1",]
top.coef <- coef[rev(order(abs(coef)))[1:20]]
barplot(sort(top.coef), horiz=T, las=1, main="Top taxa for PERMANOVA - baseline diet", cex.names=0.4)

```
```{r}
write.csv(sort(top.coef), "./outputs/beta_barplot_data_BL.csv")
```

# 3. A
## 3.1 data loading and cleaning
```{r}
otu_mat<- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/speciesBrunoOTUTable_A_033123.xlsx") # CORRECT
otu_mat<-otu_mat[!(otu_mat$otu=="FructanSensitivity"),]
row.names(otu_mat) <- otu_mat$otu
otu_mat <- as.matrix(otu_mat)
otu_mat_t = t(otu_mat)
otu_mat_t <- otu_mat_t[-1,]
class(otu_mat_t)<-"numeric"
```

```{r}
samples_df <- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/brunoMetadata_A_033123.xlsx") # CORRECT
groups<-as.list(samples_df['FsenText'])$FsenText
groups
```
## 3.2 alpha diversity
```{r}
alphaDiversity <- diversity(otu_mat_t, index="shannon")
ANOVAres <- aov(alphaDiversity~groups)

alphaDataframe <- data.frame(alphaDiversity, groups)
write.csv(alphaDataframe, "./outputs/alph_div_df_A.csv")
alphaData_Meds <- alphaDataframe %>%
  group_by(groups) %>%
  summarise(firstQ= quantile(alphaDiversity, prob=0.25, na.rm=TRUE),
            med= quantile(alphaDiversity, prob=0.5, na.rm=TRUE),
            thirdQ= quantile(alphaDiversity, prob=0.75, na.rm=TRUE))

p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity))+
        geom_boxplot(aes(col=groups))+geom_violin(aes(col=groups), alpha=0)+
        ggtitle(paste0("Fructan Diet", " p-value = ", round(summary(ANOVAres)[[1]][["Pr(>F)"]][1], 4)))+
        theme_minimal()+theme(legend.position="none")+
        ylab("Shannon Index")+xlab("fructan sensitivity")+
        geom_text(data= alphaData_Meds, aes(x= groups, y= med, label= round(med,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= firstQ, label= round(firstQ,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= thirdQ, label= round(thirdQ,2)))
p
ggsave(file="./outputs/alpha_div_A_violin.pdf", width=10, height=8, dpi=300)
```

```{r}
alphaDataframe <- data.frame(alphaDiversity, groups)
p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity)) + 
  geom_dotplot(binaxis='y', stackdir='center', aes(col=groups))+
  ggtitle("Shannon Alpha Diversity - Fructan Diet")
p
ggsave(file="./outputs/alpha_div_A.pdf", width=10, height=8, dpi=300)
```
## 3.3 beta diversity
```{r}
seqObj <- phyloseq(otu_table(as.matrix(otu_mat_t), taxa_are_rows= FALSE), sample_names(samples_df['FsenText']))
###Beta diversity
ord <- ordinate(seqObj, method = "NMDS", "bray")
NMDSNetworkData <- as.data.frame(ord["points"])
NMDSNetworkData$group <- groups


allxend <- sapply(split(NMDSNetworkData$points.MDS1, NMDSNetworkData$group), mean) # xend_calculated for each group
allyend <- sapply(split(NMDSNetworkData$points.MDS2, NMDSNetworkData$group), mean) # yend_calculated for each group
NMDSNetworkData$xend_calculated <- 0
NMDSNetworkData$yend_calculated <- 0
for (x in 1:nrow(NMDSNetworkData)) {
  NMDSNetworkData$xend_calculated[x] <- unname(allxend[NMDSNetworkData$group[x]])
  NMDSNetworkData$yend_calculated[x] <- unname(allyend[NMDSNetworkData$group[x]])
}
```

```{r}
permanova <- vegan::adonis(otu_table(seqObj)~ groups, permutations=300, method = "bray")
permanova.pval <- permanova$aov.tab[,"Pr(>F)"][1]

p <- ggplot(NMDSNetworkData,
             aes(x = points.MDS1, y = points.MDS2, xend = xend_calculated, yend = yend_calculated, color = group),
             axes=TRUE) +
        geom_point(aes(color = group)) +
        geom_edges(aes(color = group)) +
        geom_nodes(aes(color = group)) +
        xlab("NMDS1") +
        ylab("NMDS2")+
        stat_ellipse(type = "norm", linetype = 2) +
        theme_classic() +
        labs(title = paste0('Fructan Diet', " PERMANOVA p-value = ", round(permanova.pval, 4)))
p 
ggsave(file="./outputs/beta_div_A.pdf", width=10, height=8, dpi=300)
```
```{r}
pdf(file="./outputs/beta_top10_coefs_A.pdf", width=10, height=8)
coef <- coefficients(permanova)["groups1",]
top.coef <- coef[rev(order(abs(coef)))[1:20]]
barplot(sort(top.coef), horiz=T, las=1, main="Top taxa for PERMANOVA - fructan diet", cex.names=0.4)
```
```{r}
write.csv(sort(top.coef), "./outputs/beta_barplot_data_A.csv")
```

# 4. B
## 4.1 data loading and cleaning
```{r}
otu_mat<- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/speciesBrunoOTUTable_B_033123.xlsx") # CORRECT
otu_mat<-otu_mat[!(otu_mat$otu=="FructanSensitivity"),]
row.names(otu_mat) <- otu_mat$otu
otu_mat <- as.matrix(otu_mat)
otu_mat_t = t(otu_mat)
otu_mat_t <- otu_mat_t[-1,]
class(otu_mat_t)<-"numeric"
```

```{r}
samples_df <- read_excel("/Users/chenlianfu/Documents/GitHub/IBS_FructanSensitivity/diversityAnalysis/source/brunoMetadata_B_033123.xlsx") # CORRECT
groups<-as.list(samples_df['FsenText'])$FsenText
groups
```
## 4.2 alpha diversity
```{r}
alphaDiversity <- diversity(otu_mat_t, index="shannon")
ANOVAres <- aov(alphaDiversity~groups)

alphaDataframe <- data.frame(alphaDiversity, groups)
write.csv(alphaDataframe, "./outputs/alph_div_df_B.csv")
alphaData_Meds <- alphaDataframe %>%
  group_by(groups) %>%
  summarise(firstQ= quantile(alphaDiversity, prob=0.25, na.rm=TRUE),
            med= quantile(alphaDiversity, prob=0.5, na.rm=TRUE),
            thirdQ= quantile(alphaDiversity, prob=0.75, na.rm=TRUE))

p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity))+
        geom_boxplot(aes(col=groups))+geom_violin(aes(col=groups), alpha=0)+
        ggtitle(paste0("fructan sensitivity", " p-value = ", round(summary(ANOVAres)[[1]][["Pr(>F)"]][1], 4)))+
        theme_minimal()+theme(legend.position="none")+
        ylab("Shannon Index")+xlab("Maltedextrin Diet")+
        geom_text(data= alphaData_Meds, aes(x= groups, y= med, label= round(med,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= firstQ, label= round(firstQ,2)))+
        geom_text(data= alphaData_Meds, aes(x= groups, y= thirdQ, label= round(thirdQ,2)))
p
ggsave(file="./outputs/alpha_div_B_violin.pdf", width=10, height=8, dpi=300)
```

```{r}
alphaDataframe <- data.frame(alphaDiversity, groups)
p<-ggplot(alphaDataframe, aes(x=groups, y=alphaDiversity)) + 
  geom_dotplot(binaxis='y', stackdir='center', aes(col=groups))+
  ggtitle("Shannon Alpha Diversity - Maltedextrin Diet")
p
ggsave(file="./outputs/alpha_div_B.pdf", width=10, height=8, dpi=300)
```
## 3.3 beta diversity
```{r}
seqObj <- phyloseq(otu_table(as.matrix(otu_mat_t), taxa_are_rows= FALSE), sample_names(samples_df['FsenText']))
###Beta diversity
ord <- ordinate(seqObj, method = "NMDS", "bray")
NMDSNetworkData <- as.data.frame(ord["points"])
NMDSNetworkData$group <- groups


allxend <- sapply(split(NMDSNetworkData$points.MDS1, NMDSNetworkData$group), mean) # xend_calculated for each group
allyend <- sapply(split(NMDSNetworkData$points.MDS2, NMDSNetworkData$group), mean) # yend_calculated for each group
NMDSNetworkData$xend_calculated <- 0
NMDSNetworkData$yend_calculated <- 0
for (x in 1:nrow(NMDSNetworkData)) {
  NMDSNetworkData$xend_calculated[x] <- unname(allxend[NMDSNetworkData$group[x]])
  NMDSNetworkData$yend_calculated[x] <- unname(allyend[NMDSNetworkData$group[x]])
}
```

```{r}
permanova <- vegan::adonis(otu_table(seqObj)~ groups, permutations=300, method = "bray")
permanova.pval <- permanova$aov.tab[,"Pr(>F)"][1]

p <- ggplot(NMDSNetworkData,
             aes(x = points.MDS1, y = points.MDS2, xend = xend_calculated, yend = yend_calculated, color = group),
             axes=TRUE) +
        geom_point(aes(color = group)) +
        geom_edges(aes(color = group)) +
        geom_nodes(aes(color = group)) +
        xlab("NMDS1") +
        ylab("NMDS2")+
        stat_ellipse(type = "norm", linetype = 2) +
        theme_classic() +
        labs(title = paste0('Maltedextrin Diet', " PERMANOVA p-value = ", round(permanova.pval, 4)))
p 
ggsave(file="./outputs/beta_div_B.pdf", width=10, height=8, dpi=300)
```

```{r}
pdf(file="./outputs/beta_top10_coefs_B.pdf", width=10, height=8)
coef <- coefficients(permanova)["groups1",]
top.coef <- coef[rev(order(abs(coef)))[1:20]]
barplot(sort(top.coef), horiz=T, las=1, main="Top taxa for PERMANOVA - maltedextrin diet", cex.names=0.4)
```
```{r}
write.csv(sort(top.coef), "./outputs/beta_barplot_data_B.csv")
```